# Book settings
title: OpenPifPaf Guide DEV
author: Sven Kreiss
email: research@svenkreiss.com
logo: logo.png
discription: Guide for OpenPifPaf (dev version).

# latex:
#   latex_documents:
#     targetname: book.tex

html:
  favicon: favicon.png
  extra_navbar: This is the dev version of the Guide. Here is the <a href="https://vita-epfl.github.io/openpifpaf/">stable version</a>.

# Information about where the book exists on the web
repository:
  url                       : https://github.com/vita-epfl/openpifpaf  # Online location of your book
  path_to_book              : guide  # Optional path to your book, relative to the repository root
  branch                    : dev  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  binderhub_url             : "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
